stop method
MinaroShikuchi/mouton pull request #8
Opened 2022-01-27 16:16 UTC by MinaroShikuchi

2022-01-28 14:28 UTC, NathanPo requested changes

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Characters/playable_character.cpp
> +
%20 supprime la ligne

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Characters/playable_character.cpp
> +
vide*

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Characters/playable_character.cpp
> +
same

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Characters/playable_character.h
> +    double       speed = 5;
obliger ? de mettre = 5

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.cpp
> +
C'est trop

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.cpp
> +
MAIS...............; !

2022-01-28 14:28 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.h
> +  int movement_timer = 0;
hmm on est obligé de set a 0 ?

2022-01-29 13:59 UTC, MinaroShikuchi commented on Project_SDL_Part1_base/Characters/playable_character.h
> +    double       speed = 5;
nan c'est bien au moins il trace

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Characters/shepherd.cpp
> +    : PlayableCharacter("../media/shephard.png", window_surface_ptr_) {}
peut être renommer l'image ?

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.cpp
> +        std::make_unique<Sheep>(this->window_surface_ptr_);
ne voit pas forcément l'intérêt d’être sur deux lignes

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.cpp
>      // std::unique_ptr<Animal> sheep(new Sheep(this->window_surface_ptr_));
Obliger de laisser les coms ??

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Game/application.cpp
> +        std::make_unique<Sheep>(this->window_surface_ptr_);
si c'est le correcteur auto c good pour moi :)

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Game/ground.h
> +#include "../constants.h"
on ne peut pas faire ../Characters/*.h ??

2022-01-29 14:00 UTC, NathanPo commented on Project_SDL_Part1_base/Game/ground.h
> +  add_playable_character(std::unique_ptr<PlayableCharacter> playableCharacter);
weird

2022-01-29 14:25 UTC, MinaroShikuchi commented on Project_SDL_Part1_base/Game/ground.h
> +#include "../constants.h"
je sais pas

2022-01-29 14:26 UTC, MinaroShikuchi commented on Project_SDL_Part1_base/Game/ground.h
> +  add_playable_character(std::unique_ptr<PlayableCharacter> playableCharacter);
?

2022-01-29 14:30 UTC, merged